
apiVersion: v1
kind: Service
metadata:
  name: service-for-team-player-service
spec:
  type: ClusterIP
  selector:
    app: teap-player-service
  ports:
    - name: app-http-listener
      protocol: TCP
      port: 8080
      targetPort: 80
    - name: app-grpc-listener
      protocol: TCP
      port: 5064
      targetPort: 5064
  